In [1]:
conda install -c anaconda numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.2                |           py37_0         3.1 MB  anaconda
    openssl-1.1.1d             |       he774522_2         5.7 MB  anaconda
    ------------------------------------------------------------
                                           Total:         8.8 MB

The following packages will be UPDATED:

  conda                      pkgs/main::conda-4.7.12-py37_0 --> anaconda::conda-4.8.2-py37_0

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl                                         pkgs/main --> anaconda




conda-4.8.2          | 3.1 MB    |            |   0% 
conda-4.8.2          | 3.1 MB    |            |   1% 
conda-4.8.2          | 3.1 MB   



==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base -c defaults conda



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3




# numpy array

In [2]:
import numpy as np

In [22]:
nums_1d = [1,2,3] # 1d matrix

In [23]:
nums_1d = np.array(nums_1d)

In [28]:
nums_1d

array([1, 2, 3])

In [29]:
nums_1d.ndim  # To know about the dimentions of array we use "arrayname.ndim"

1

In [30]:
nums_1d.shape # To know about the shape array we use "arrayname.shape"

(3,)

In [12]:
nums_2d = [[1,2,3],[4,5,6]] # 2d matrix

In [13]:
nums_2d = np.array(nums_2d)

In [14]:
nums_2d
nums_2d.ndim

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
nums_3d = [[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]] # 3d matrix
nums_3d = np.array(nums_3d)
nums_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 4]]])

In [20]:
nums_3d.ndim

3

In [31]:
nums_3d.shape

(2, 2, 3)

In [36]:
#nump array only store one type of data 
# numpy arrays are fater ther python list 

In [48]:
nums_str = [1,2,3,True] # if any entry in array is string it become string
# if any entry in array of int, bool, foat is float then it convert all the entries/ values to float
# if any entry in array of int, bool is int then it convert all the entries/ values to int

In [49]:
nums_str = np.array(nums_str)

In [50]:
nums_str.dtype

dtype('int32')

In [51]:
nums_str

array([1, 2, 3, 1])

# Functions in numpy

In [52]:
# Functions in Numpy
# zeros, Ones , eye , diag , randint , rand , randn 

In [53]:
arr = np.zeros(5) 
arr

array([0., 0., 0., 0., 0.])

In [54]:
arr = np.zeros((2,3)) # in this tuple containing the number of rows and columns
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
arr = np.ones((2,3)) 
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [6]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [9]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
arr = np.eye(3,4)
np.diag(arr)

array([1., 1., 1.])

In [13]:
rand_arr = np.random.randint(1,20,4)# it include any random numbers in between 1 and 20 but 20 is excluded
rand_arr

array([12, 14, 12,  5])

In [15]:
rand_arr = np.random.rand(4) # it gives the any random 4 numbers between 0 and 1 in 1D array
rand_arr

array([0.388127  , 0.07208821, 0.36419797, 0.44233179])

In [16]:
rand_arr = np.random.rand(10)# it gives the any random 10 numbers between 0 and 1 in 1D array
rand_arr

array([0.09486853, 0.55652034, 0.6847667 , 0.68166733, 0.91540573,
       0.3069705 , 0.22593553, 0.06959348, 0.45776779, 0.77736929])

In [17]:
rand_arr = np.random.rand(2,3)# it gives the any random numbers between 0 and 1 in 2D array 
rand_arr

array([[0.11292242, 0.98796935, 0.85969448],
       [0.32959791, 0.33918994, 0.16535857]])

In [20]:
rand_arr = np.random.randn(3)# it gives the any random numbers close to 0 and it will be +ve numbers as well as -ve numbers
rand_arr

array([ 3.17782416,  0.44099325, -0.68558926])

In [21]:
rand_arr = np.random.randn(2,3)
rand_arr

array([[-0.36160436,  1.08913221,  1.23220214],
       [-1.56619198, -0.24482518, -0.4937997 ]])

In [24]:
rand_arr = np.random.randn(10) # its mean is alway close to zero
np.mean(rand_arr)

0.14959633843213516

In [ ]:
)