In [1]:
import numpy as np

# 1-d Array

### Indexing

In [2]:
#  indexes      0   1  2  3  4  5
arr = np.array([10,11,12,13,14,15])
# indexes       -6 -5 -4 -3 -2 -1
arr

array([10, 11, 12, 13, 14, 15])

In [3]:
arr[0] # by putting the index we get the value stored at that index

10

In [4]:
arr[-1]

15

### Slicing

In [5]:
arr[0:3] # it returns the 0,1,2 indexes values but it doesnt return the third index value because the last boundry is excluded

array([10, 11, 12])

In [6]:
arr[1:]#its take 1 as starting index & the empty last boundry mean it returns the values to last index & last index in included

array([11, 12, 13, 14, 15])

In [7]:
arr[:] #it returns all the values from starting index to last index 

array([10, 11, 12, 13, 14, 15])

In [8]:
arr[-3:] #it takes the values from  -3 index to -1 index as end boundry is not defined so -1 is included 

array([13, 14, 15])

In [9]:
arr[:-1] #it takes the values from -1 index to the last index as end boundry is defined so -1 index is excluded 

array([10, 11, 12, 13, 14])

In [10]:
arr[1:4:2] # its gives the values after the jump of 2 indexes 

array([11, 13])

# 2d Array

### Creating 2-d Array

In [11]:
matrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
matrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## Indexing

### 1. indexing using double bracket notation

In [12]:
matrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [13]:
matrix[0][1] #first[] is used for the index on which the first arry is,2nd[] is used for the indexes with in the selected array 

12

In [14]:
matrix[2][2]

33

### 2. indexing using single bracket notation (Recommended)

In [15]:
matrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [16]:
matrix[1,2] 
#1st value is used for the index on which the first arry is
#2nd value is used for the indexes with in the selected array 

23

In [17]:
matrix[0,2]

13

In [18]:
matrix[2,0]

31

# 3. Slicing 

## Slicing using single bracket notation  

In [19]:
matrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [20]:
# we want to extract 
# [[11 12]
#  [21 22]]

In [22]:
matrix[:2, :2]

array([[11, 12],
       [21, 22]])

In [23]:
# we want to extract 
# [[22 23]
#  [32 33]]

In [24]:
matrix[1:, 1:]

array([[22, 23],
       [32, 33]])

In [27]:
np.random.seed(123)
matrix2 = np.random.randint(1,101,49).reshape(7,7)
matrix2

array([[ 67,  93,  99,  18,  84,  58,  87],
       [ 98,  97,  48,  74,  33,  47,  97],
       [ 26,  84,  79,  37,  97,  81,  69],
       [ 50,  56,  68,   3,  85,  40,  67],
       [ 85,  48,  62,  49,   8, 100,  93],
       [ 53,  98,  86,  95,  28,  35,  98],
       [ 77,  41,   4,  70,  65,  76,  35]])

In [28]:
# we want to extract
# 48,  74,  33
# 79,  37,  97
# 68,   3,  85
# 62,  49,   8

In [31]:
matrix2[1:5, 2:5]

array([[48, 74, 33],
       [79, 37, 97],
       [68,  3, 85],
       [62, 49,  8]])