In [1]:
import numpy as np

In [2]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,3)

In [3]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [5]:
#np.sum(matrix)
matrix.sum()
# sum function gives the sum of all the values in matrix  

39

In [6]:
# row = 1 , column = 0

In [7]:
np.min(matrix, axis=1) # it gives the out of the minimum number in each row of matrix

array([3, 2, 1])

In [8]:
np.min(matrix, axis=0) # it gives the out of the minimum number in each column of matrix

array([2, 2, 1])

In [10]:
np.max(matrix, axis=1) # it gives the out of the maximum number in each row of matrix

array([ 7, 10,  7])

In [11]:
np.max(matrix, axis=0) # it gives the out of the maximun number in each column of matrix

array([ 7,  4, 10])

In [12]:
np.sum(matrix) # it gives the out of the sum of all the values in the matrix

39

In [13]:
np.sum(matrix, axis=0) # it gives the out of the sum of  each column of matrix

array([12,  9, 18])

In [14]:
np.sum(matrix, axis=1) # it gives the out of the sum of  each row of matrix

array([13, 16, 10])

In [15]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [16]:
np.cumsum(matrix, axis=0) # it gives the out of the sum of  each column of matrix

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)