In [1]:
import numpy as np

In [6]:
arr = np.array([71,2,6,10,7,80])

In [7]:
np.min(arr)

2

In [8]:
np.max(arr)

80

In [9]:
np.argmin(arr)

1

In [10]:
np.argmax(arr)

5

In [12]:
np.sqrt(arr)

array([8.42614977, 1.41421356, 2.44948974, 3.16227766, 2.64575131,
       8.94427191])

In [13]:
np.exp(arr)

array([6.83767123e+30, 7.38905610e+00, 4.03428793e+02, 2.20264658e+04,
       1.09663316e+03, 5.54062238e+34])

In [16]:
np.sin(arr)

array([ 0.95105465,  0.90929743, -0.2794155 , -0.54402111,  0.6569866 ,
       -0.99388865])

In [17]:
np.cos(arr)

array([-0.30902273, -0.41614684,  0.96017029, -0.83907153,  0.75390225,
       -0.11038724])

In [18]:
np.linspace(1,50,15)

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

In [19]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [20]:
arr1 = np.array([1,0,1,1,0,1,0],dtype='bool')

In [21]:
arr1

array([ True, False,  True,  True, False,  True, False])

In [23]:
for i in arr1:
    print(i)

True
False
True
True
False
True
False
