In [1]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5,6,7])

In [13]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14])

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [16]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [17]:
arr **3

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [18]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [20]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
arr/0 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [23]:
1/0

ZeroDivisionError: division by zero