In [1]:
import numpy as np

In [2]:
rand_arr = np.random.randint(1,100,20)
rand_arr

array([15, 35, 93, 71, 76, 60, 34, 26, 97, 83, 69, 11, 44, 91, 93, 19, 53,
       13, 64, 20])

In [4]:
rand_arr.shape

(20,)

In [9]:
rand_arr.ndim

1

In [10]:
arr = rand_arr.reshape(2,10)
arr

array([[15, 35, 93, 71, 76, 60, 34, 26, 97, 83],
       [69, 11, 44, 91, 93, 19, 53, 13, 64, 20]])

In [6]:
arr.shape

(2, 10)

In [7]:
arr.ndim

2

In [11]:
arr = arr.reshape(20)
arr

array([15, 35, 93, 71, 76, 60, 34, 26, 97, 83, 69, 11, 44, 91, 93, 19, 53,
       13, 64, 20])

In [12]:
arr.shape

(20,)

In [13]:
arr.ndim

1

In [15]:
arr = arr.reshape(5,2,2)
arr

array([[[15, 35],
        [93, 71]],

       [[76, 60],
        [34, 26]],

       [[97, 83],
        [69, 11]],

       [[44, 91],
        [93, 19]],

       [[53, 13],
        [64, 20]]])

In [16]:
arr.shape

(5, 2, 2)

In [17]:
arr.ndim

3

In [27]:
arr = np.arange(1,11) # 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
arr.reshape(2,-1) # -1 auto get the numbers of columns depend on numbers of rows

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
arr.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
arr = np.arange(1,111)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [32]:
arr.reshape(-1,5) # -1 auto get the numbers of rows depend on numbers of columns

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

# Generate same random number every time

In [33]:
arr = np.random.randint(1,111,14)
arr

array([ 54,  39,  85,  18,  16, 107,  29,  19, 104,  69, 107,  42,  48,
         7])

# Seed Function

In [35]:
np.random.seed(121)
arr = np.random.randint(1,101,10)
arr

array([67, 86,  9, 96, 66, 53, 84, 97, 47, 35])

In [36]:
arr.size # use to find the size of array 

10