In [1]:
import numpy as np

# View

In [7]:
arr = np.array([1,2,3,4,5])

In [8]:
sliced_arr = arr[1:4] 
# it creat the view of the arr 
# it doesnot allocate any other memory location in memory 
# As we performed any operation on sliced_arr , it effects the arr

In [9]:
sliced_arr

array([2, 3, 4])

In [12]:
sliced_arr[:] = 0 
# we make all the entries/ values in the sliced_arr 0 
# Those values are also updted in the arr 

In [13]:
sliced_arr

array([0, 0, 0])

In [14]:
arr

array([1, 0, 0, 0, 5])

In [15]:
# As we change the values in slided_arr those chages are also presednt in arr , sliced_arr is the view of arr 

# Copy

In [16]:
arr = np.array([1,2,3,4,5])

In [19]:
sliced_arr = arr[1:4] .copy()
# it creat the the copy from the arr we use .copy() function
# it allocates memory location in memory 
# As we performed any operation on sliced_arr , it doesn't effects the arr

In [20]:
sliced_arr

array([2, 3, 4])

In [21]:
sliced_arr[:] = 0 

In [22]:
sliced_arr

array([0, 0, 0])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
# As we see their is no effect of any change in sliced_arr on arr